In [1]:
from arango import ArangoClient, ServerVersionError
from datetime import datetime, timedelta
from ollama import Client

import getpass
import json
import os
import random
import threading
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor, as_completed
from multiprocessing import Lock
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm.notebook import tqdm

## Functions
##### Run Cells to Continue

In [2]:
def connect_to_arango_client(host: str):
    try:
        client = ArangoClient(hosts=host)
    except:
        print(f'{get_timestamp()} -- Could not connect to ArangoDB client at "{host}"')
        return None
    
    return client

In [3]:
def connect_to_arango_db(client: ArangoClient, db_name: str, username: str, password: str, max_retries: int = 3): 
    retries = 0
    if password is None:
        password = getpass.getpass(f'Please enter the password for user {username} for access to the {db_name} database: ')
        
    while retries < max_retries:
        try:
            db = client.db(db_name, username=username, password=password)     
            vers = db.version()
            print(f'{get_timestamp()} -- Successfully connected to database {db_name} running version {vers}.')
            return db
        except (ConnectionAbortedError, ServerVersionError) as e:
            retries += 1
            print(f'{get_timestamp()} -- Connection refused for db {db_name}.')
            password = getpass.getpass(f'Input password to try again:  ')
        except Exception as e:
            print(f'\n**** {type(e)}: {e} ****\n')
            retries += 1
            print(f'{get_timestamp()} -- Could not connect to db "{db_name}".')
    
    return None

In [4]:
def without(d, keys):
    new_d = d.copy()
    for key in keys:
        if key in d.keys():
            new_d.pop(key)
    return new_d

In [5]:
def get_timestamp(str_format: str = "%Y-%m-%d %H:%M:%S"):
    return datetime.now().strftime(str_format)

def connect_to_arango_client(host: str):
    try:
        client = ArangoClient(hosts=host)
    except:
        print(f'{get_timestamp()} -- Could not connect to ArangoDB client at "{host}"')
        return None
    
    return client


def connect_to_arango_db(client: ArangoClient, db_name: str, username: str, password: str, max_retries: int = 3): 
    retries = 0
    if password is None:
        password = getpass.getpass(f'Please enter the password for user {username} for access to the {db_name} database: ')
        
    while retries < max_retries:
        try:
            db = client.db(db_name, username=username, password=password)     
            vers = db.version()
            print(f'{get_timestamp()} -- Successfully connected to database {db_name} running version {vers}.')
            return db
        except (ConnectionAbortedError, ServerVersionError) as e:
            retries += 1
            print(f'{get_timestamp()} -- Connection refused for db {db_name}.')
            password = getpass.getpass(f'Input password to try again:  ')
        except Exception as e:
            print(f'\n**** {type(e)}: {e} ****\n')
            retries += 1
            print(f'{get_timestamp()} -- Could not connect to db "{db_name}".')
    
    return None

In [6]:
def exec_aql_query(aql, query):
    cursor = aql.execute(query)
    return cursor

In [7]:
def get_steps_for_all_ttps(aql, graph_name):
    ttp_steps_query = """
        LET step_collections = ["DevelopmentStep", "PlanningStep", "ExecutionStep"]

            FOR ttp IN TTPArtifact
                LET refs = (
                    FOR a IN INBOUND ttp GRAPH '""" + graph_name + """'    // *Artifact → TTPArtifact
                        FOR s IN INBOUND a GRAPH '""" + graph_name + """'   // *Step → *Artifact
                            LET step_type = SPLIT(s._id, "/")[0]
                            FILTER step_type IN step_collections
                            COLLECT stepType = step_type INTO grouped_artifacts = a
                            RETURN {
                                step_type: stepType,
                                reference_count: LENGTH(grouped_artifacts),
                                artifact_keys: UNIQUE(FOR g IN grouped_artifacts RETURN g._key)
                            }
                )
                RETURN {
                    ttp_key: ttp._key,
                    references_by_step_type: refs
                }
    """
    
    cursor = aql_query_graph(aql, ttp_steps_query)
    
    ttp_steps = [doc for doc in cursor]

    return ttp_steps

In [8]:
def get_sample_pairs_from_graph(db, aql, graph_name, 
                                n_samples=5, 
                                pairs_per_sample=5, 
                                src_filter_str='', 
                                pairs_filter_str='', 
                                src_collections=[], 
                                pairs_collections=[],
                                exclude_src_collections=[],
                                exclude_pairs_collections=[]
                               ):
    graph = db.graph(graph_name)

    # Get all vertex collections in the graph
    vertex_collections = graph.vertex_collections()
    if len(src_collections) == 0:
        src_collections = vertex_collections
    if len(pairs_collections) == 0:
        pairs_collections = vertex_collections
    
    src_included_collections = [coll for coll in vertex_collections if coll in src_collections and coll not in exclude_src_collections] 
    pairs_included_collections = [coll for coll in vertex_collections if coll in pairs_collections and coll not in exclude_pairs_collections]

    
    # Sample n nodes from each collection
    sampled_nodes = []
    limit_str = f'LIMIT {n_samples}' if n_samples > 0 else ''
    src_filter_str = f'FILTER {src_filter_str}' if src_filter_str != '' else ''
    pairs_filter_str = f'FILTER {pairs_filter_str}' if pairs_filter_str != '' else ''
    
    for vc in src_included_collections:
        query = f"""
        FOR doc IN {vc}
            {src_filter_str}
            SORT RAND()
            {limit_str}
            RETURN doc
        """
        result = list(aql.execute(query, batch_size=1000))
        #print(f'**** Len results: {len(result)} ****')
        sampled_nodes.extend([without(doc, ['_rev']) for doc in result])


    # Fetch all node documents (to choose random m for pairing) ---
    # Build a union query to get all documents from all vertex collections
    union_parts = [f"FOR doc IN {vc} {pairs_filter_str} RETURN doc" for vc in pairs_included_collections]
    all_docs_query = f"RETURN UNION({', '.join(union_parts)})" if len(pairs_included_collections) > 1 else union_parts[0]
    #print(f'all_docs_query:\n{all_docs_query}')

    cursor = list(aql.execute(all_docs_query, batch_size=10000))
    #print(isinstance(list(cursor)[0], dict))
    all_docs = [without(doc, ['_rev']) for batch in cursor for doc in batch] if len(pairs_included_collections) > 1 else [without(doc, ['_rev']) for doc in cursor]
    #print(all_docs[0])
    all_docs_by_id = {doc["_id"]: doc for doc in all_docs}
    
    # Build pairings
    pairings = []
    
    for node in sampled_nodes:
        node_id = node["_id"]
        
        # Exclude the current node from the pool
        candidates = [doc for doc_id, doc in all_docs_by_id.items() if doc_id != node_id]
        
        # Randomly sample m candidates
        if len(candidates) < pairs_per_sample or pairs_per_sample < 1:
            sampled = candidates
        else:
            sampled = random.sample(candidates, pairs_per_sample)

        #print(f'*** len(pairs): {len(sampled)} ***')
        pairings.append({'src_node': node, 'pair_nodes': sampled})

    return pairings

In [9]:
def get_graph_edges(db, aql, graph_name, include_node_docs=False):
    graph = db.graph(graph_name)
    valid_edges = []
    # Loop through edge definitions in the graph
    for ed in graph.edge_definitions():
        edge_collection = ed["edge_collection"]
        #print(ed)
        from_colls = ed["from_vertex_collections"]
        to_colls = ed["to_vertex_collections"]
    
        # Build AQL query for this edge definition
        # Accept any valid (from, to) pair from the defined collections
        filters = []
        for from_coll in from_colls:
            for to_coll in to_colls:
                filters.append(
                    f"(IS_SAME_COLLECTION(edge._from, '{from_coll}') && IS_SAME_COLLECTION(edge._to, '{to_coll}'))"
                )
        
        filter_clause = " || ".join(filters)
    
        aql_query = f"""
        FOR edge IN {edge_collection}
            FILTER {filter_clause}
            RETURN edge
        """
    
        result = list(aql.execute(aql_query, batch_size=1000))
        if include_node_docs:
            for edge in result:
                #print(edge)
                edge['_from_node'] = db.collection(edge['_from'].split('/')[0]).get(edge['_from'])
                edge['_to_node'] = db.collection(edge['_to'].split('/')[0]).get(edge['_to'])
                edge['type'] = edge_collection
            result = [edge for edge in result if edge['_from_node'] is not None and edge['_to_node'] is not None]
            
        valid_edges.extend(result)
    return valid_edges

In [10]:
def update_edgecoll_fields(db, aql, rename_fields={}, collections=[]):
    # --- Get all edge collections in the DB ---
    all_collections = db.collections()
    #rint(all_collections)
    edge_collections = [c["name"] for c in all_collections if c["type"] == 'edge'] if len(collections) == 0 else collections
    print(f"Found {len(edge_collections)} edge collections in the database.")
    
    # Build the merge dict part: { new_field: doc.old_field, ... }
    merge_fields = ", ".join(
        f"{new_field}: doc.{old_field}" for old_field, new_field in rename_fields.items()
    )

    # Build list of old fields to unset
    old_fields_list = ", ".join(f"'{old_field}'" for old_field in rename_fields.keys())
    
        # --- Run update on each edge collection ---
    for ec in edge_collections:
        print(f"Updating edge collection: {ec}")
        aql_query = f"""
        FOR doc IN {ec}
            FILTER {" || ".join(f"HAS(doc, '{old_field}')" for old_field in rename_fields.keys())}
            LET updated = UNSET(MERGE(doc, {{
                {merge_fields}
            }}), [{old_fields_list}])
            UPDATE doc WITH updated IN {ec}
        """
        print(aql_query)
        aql.execute(aql_query)
        print(f"Done updating {ec}")
    
    print("All edge documents updated.")

In [11]:
def show_n_ttps(ttps: list, n: int = 5, sort_on: str = None, from_end: str = 'top'):
    if from_end == 'top':
        if sort_on is not None:
            ttps = sorted(ttps, key=lambda x: x[sort_on], reverse=True)
        ttp_slice = ttps[:n]
        header_str_end = 'Top'
    elif from_end == 'bot':
        if sort_on is not None:
            ttps = sorted(ttps, key=lambda x: x[sort_on], reverse=False)
        ttp_slice = ttps[-n:]
        header_str_end = 'Bottom'
    else:
        print(f'Invalid value for from_end: {from_end}. Expected "top" or "bot".')

    header_str = f'********** {header_str_end} {n} TTPs **********'
    h_str_len = len(header_str)
    print(header_str)
    print('-'*h_str_len)
    print(f'   {"TTP":<13}|  {"References":<10}')
    print('-'*h_str_len)
    for ttp in ttp_slice:
        print(f'   {ttp["ttp_key"]:<13}|  {ttp["refs"]:>9}')

In [12]:
def plot_ttp_artifact_histogram(data: list[dict], save_to_file: bool = False, save_file: str = 'ttp_hist.png'):
    # Extract all unique step_types across all entries
    step_types = sorted({
        step['step_type']
        for entry in data
        for step in entry.get('references_by_step_type', [])
    })

    ttp_keys = [entry['ttp_key'] for entry in data]
    n = len(ttp_keys)
    x = np.arange(n)  # x positions for each ttp_key

    width = 0.5 / max(len(step_types), 1)  # dynamic bar width based on number of step_types

    # Prepare counts per step_type aligned with ttp_keys
    counts_per_step = {step: [] for step in step_types}
    total_counts = []
    for entry in data:
        step_count_map = {step['step_type']: step['reference_count'] for step in entry.get('references_by_step_type', [])}
        total = 0
        for step in step_types:
            count = step_count_map.get(step, 0)
            counts_per_step[step].append(step_count_map.get(step, 0))
            total += count
        total_counts.append(total)

    fig, ax = plt.subplots(figsize=(max(8, n), 5))

    # Plot bars for each step_type with proper offsets
    for i, step in enumerate(step_types):
        offset = (i - (len(step_types) - 1) / 2) * width
        ax.bar(x + offset, counts_per_step[step], width, label=step)

    # total counts bar
    ax.plot(x, total_counts, color='orchid', label='Total References', linewidth=0.7, linestyle='--')

    
    # Formatting
    ax.set_xlabel('TTP')
    ax.set_ylabel('Reference Count')
    ax.set_title('Reference Counts per Step Type for each TTP and Total per TTP')
    ax.set_xticks(x)
    ax.set_xticklabels(ttp_keys, rotation=45, ha='right')
    ax.legend(title="Step Type")
    ax.grid(axis='y', linestyle='--', alpha=0.3)
    plt.tight_layout()
    if save_to_file:
        fig.savefig(save_file)
    plt.show()

In [13]:
def almost_in_list(truth_list, edge, key, possible_maps={'suggested_vals': [], 'truth_vals': []}):
    if edge in truth_list:
        return True
    for sval in possible_maps['suggested_vals']:
        for tval in possible_maps['truth_vals']:
            edge_copy = edge.copy()
            edge_copy[key] = tval if edge[key] == sval else edge[key]
            if edge_copy in truth_list:
                return True
    return False

In [14]:
def prompt_and_response(client, model, prompt, sys_set=None, quiet=False, stream=True, options={}):
    p_start = datetime.now()
    response = ''
    try:
        for part in client.generate(model=model, prompt=prompt, stream=stream, options=options):
            response += part['response']
            if not quiet:
                print(part['response'], end='', flush=True)
    except Exception as e:
        print(f'ERROR: {e}\nSkipping prompt...')
        return None
    p_end = datetime.now() - p_start
    if not quiet:
        print(f'Prompt took {p_end}')
    return response

In [15]:
def part1_prompt(edge_pairs, oll_client, model='gemma3:27b-it-qat', quiet=True, options={'temperature': 0.8}, src_node_key='src_node', pair_node_key='pair_node'):
    part1_responses = []
    max_pairs_listed = 10
    prompts_start = datetime.now()
    edge_pairs
    pairings = [
        {
            'src_node': edge[src_node_key], 
            'pair_node': edge[pair_node_key]
        } for edge in edge_pairs if edge[src_node_key] is not None and edge[pair_node_key] is not None
    ]
    
    for node_pair in tqdm(pairings, desc='Prompt 1', leave=False):
        #print(node_pair)
        #print(node_pair["src_node"]["_id"])
        
        prompt = f"""Act as a data analyzer. Consider the following data for a graph network, as a source node and a destination node:
        {json.dumps(node_pair)}
        
        Should an edge exist between these two nodes?
        Answers should be in the form of True or False..
        
        Do not provide any conversation, only the boolean True/False as your answer.
        """
        #print()
        #print(len(prompt))
        
        response = prompt_and_response(oll_client, model, prompt, quiet=quiet, options=options)
        if response is not None:
            #print(type(response))
            j_response = {
                'src_node': node_pair['src_node'],
                'pair_node': node_pair['pair_node'],
                'is_connected': response
            }
            part1_responses.append(j_response)
        else:
            if not quiet:
                print(f'Response for {node_pair['src_node']['_id']} -> {node_pair['pair_node']['_id']} is None.')
        
    
    prompts_total = datetime.now() - prompts_start
    if not quiet:
        print(f'***** Prompts took a total of: {prompts_total} *****')

    return part1_responses

In [16]:
def part2_prompt(part1_responses, oll_client, model='llama3.3:70b', quiet=True, options={'temperature': 0.8}):
    part2_responses = []
    max_pairs_listed = 10
    prompts_start = datetime.now()
    pairings = [
        {
            'src_node': edge['src_node'], 
            'pair_node': edge['pair_node']
        } for edge in part1_responses if edge['is_connected'] #get_graph_edges(db, aql, graph_name, include_node_docs=True) if edge['_from_node'] is not None and edge['_to_node'] is not None
    ]
    
    for node_pair in tqdm(pairings, desc='Prompt 2', leave=False):
        #print(json.dumps(node_pair, indent=4))
        #print(node_pair["src_node"]["_id"])
        
        prompt = f"""Act as a data analyzer. Consider the following data for a graph network, as a source node and a destination node:
        {json.dumps(node_pair)}
        
        What relationship or edge type is most likely between these two nodes? Justify with field-level analysis.
        The edge should be one of the following types: 
            - LEADS_TO : a sequential relationship where node A directly precedes node B
            - REFERENCES : a relationship where node B provides insights for the production or completion of node A
            - CONTAINS : a realtionship where node A contains an instance of node B or node B is a part of node A, e.g., a process CONTAINS a step because a step is part of the process
            - PRODUCES : node A produces node B, e.g., a planning step produces a planning document
        Answers should be in the form of 1 single JSON object (not a list) such as below, with 0 or 1 entry per pair:    
        '{{"src_attr": "<src_node_attribute>", "dest_attr": "<pair_node_attribute>", "explanation": "<1 sentence explanation of why the nodes are connected>"}}'.
        For Example:
        {{"src_attr": "attribute1", "dest_attr": "attribute3", "type": "REFERENCES", "explanation": "destination node's attribute3 field is related to the source node's attribute 1 field"}}
    
        If there are no obvious explicit connections, set the explanation to "NO CONNECTION".
        
        Do not provide any conversation, only the JSON object as your answer.
        """
        #print()
        #print(len(prompt))
        
        response = prompt_and_response(oll_client, model, prompt, quiet=quiet, options=options)
        if response is not None:
            #print(response)
            if isinstance(response, list):
                for r in response:
                    r = json.loads(r.replace('```json', '').replace('```', '')) 
                    r['_from'] = node_pair['src_node']['_id']
                    r['_to'] = node_pair['pair_node']['_id']
                    r['src_node'] = node_pair['src_node']
                    r['pair_node'] = node_pair['pair_node']
                    part2_responses.append(r)
            else:
                response = json.loads(response.replace('```json', '').replace('```', '')) 
                response['_from'] = node_pair['src_node']['_id']
                response['_to'] = node_pair['pair_node']['_id']
                response['src_node'] = node_pair['src_node']
                response['pair_node'] = node_pair['pair_node']
                part2_responses.append(response)
        else:
            if not quiet:
                print(f'Response for {node_pair['src_node']['_id']} -> {node_pair['pair_node']['_id']} is None.')
        
    
    prompts_total = datetime.now() - prompts_start
    if not quiet:
        print(f'***** Prompts took a total of: {prompts_total} *****')

    return part2_responses

In [17]:
def part3_prompt(part2_responses, oll_client, model='gemma3:27b-it-qat', quiet=True, options={'temperature': 0.8}):
    part3_responses = []
    max_pairs_listed = 10
    prompts_start = datetime.now()
    pairings = [
        {
            'src_node': edge['src_node'], 
            'pair_node': edge['pair_node']
        } for edge in part2_responses #get_graph_edges(db, aql, graph_name, include_node_docs=True) if edge['_from_node'] is not None and edge['_to_node'] is not None
    ]
    
    for i in tqdm(range(0, len(pairings)), desc='Prompt 3', leave=False):
        node_pair = pairings[i]
        #print(node_pair)
        #print(node_pair["src_node"]["_id"])
        
        prompt = f"""
        Act as a data analyzer. Consider the following data for a graph network, as a source node and a destination node:
        {json.dumps(node_pair)}
        
        Rate the strength and accuracy of a potential connection from 1-10.
        Answers should be in the form of an integer between 1 and 10.
        
        Example output: "9"
        Think through this problem and then provide me ONLY the conclusion. Do not show your reasoning process in the final answer.    
        """
        #print()
        #print(len(prompt))
        
        response = prompt_and_response(oll_client, model, prompt, quiet=quiet, options=options)
        if response is not None:
            #print(response)
            j_response = {
                'src_node': node_pair['src_node'],
                'pair_node': node_pair['pair_node'],
                '_from': node_pair['src_node']['_id'],
                '_to': node_pair['pair_node']['_id'],
                'type': part2_responses[i]['type'],
                'explanation': part2_responses[i]['explanation'],
                'src_attr': part2_responses[i]['src_attr'],
                'dest_attr': part2_responses[i]['dest_attr'],
                'conn_strength': int(response),
                'status': 'success:p3'
            }
            part3_responses.append(j_response)
        else:
            if not quiet:
                print(f'Response for {node_pair['src_node']['_id']} -> {node_pair['pair_node']['_id']} is None.')
            """j_response = {
                'src_node': p2_response['src_node'],
                'pair_node': p2_response['pair_node'],
                '_from': p2_response['src_node']['_id'],
                '_to': p2_response['pair_node']['_id'],
                'type': p2_response['type'],
                'explanation': p2_response['explanation'],
                'src_attr': p2_response['src_attr'],
                'dest_attr': p2_response['dest_attr'],
                'conn_strength': int(response),
                'status': f'ERROR: {}'
            }"""
        
    
    prompts_total = datetime.now() - prompts_start
    if not quiet:
        print(f'***** Prompts took a total of: {prompts_total} *****')

    return part3_responses

In [18]:
def append_json_to_file(new_entry, file_path, write_lock):
    with write_lock:
        # Check if file exists
        with open(file_path, 'a') as file:
            file.write(json.dumps(new_entry, default=str) + '\n')

## Variables and Setup

In [19]:
############ USER VARIABLES ############
ar_host = 'http://localhost:8529'
db_name = 'Process_Test'
username = 'root'
graph_name = 'Test_Process'

oll_host = 'http://10.10.80.99:4001'
GEMMA3_27B_MODEL = 'gemma3:27b-it-qat'
GEMMA3_12B_MODEL = 'gemma3:12b-it-qat'
LLAMA3_3_70B_MODEL = 'llama3.3:70b'
MAGISTRAL_24B_MODEL = 'magistral:24b'
CODELLAMA_70B_MODEL = 'codellama:70b'
DEEPSEEK_R1_70B_MODEL = 'deepseek-r1:70b'
#oll_sys_settings = "You are a specialized software for assisting in creating graph networks. You will receive node data and provide edge definitions as output in JSON format. Do not engage in any conversation."

n_samples = 10
pairs_per_sample = 40
src_filter_str = ''
pairs_filter_str = ''
src_collections = []
pairs_collections = [] #['TTPArtifact']
exclude_src_collections = ['Process', 'PlanningStep', 'DevelopmentStep', 'ExecutionStep', 'TTPArtifact']
exclude_pairs_collections = ['Process', 'PlanningStep', 'DevelopmentStep', 'ExecutionStep', 'TTPArtifact']
########## END USER VARIABLES ##########

In [20]:
password = getpass.getpass(f'Please enter the password for user {username} for access to the {db_name} database: ')

Please enter the password for user root for access to the Process_Test database:  ········

In [21]:
ar_client = connect_to_arango_client(ar_host)
db = connect_to_arango_db(ar_client, db_name, username, password)
aql = db.aql
oll_client = Client(host=oll_host)

2025-10-22 09:45:04 -- Successfully connected to database Process_Test running version 3.12.5-2.

In [22]:
pairings = get_sample_pairs_from_graph(db, aql, graph_name, 
                                       n_samples=n_samples, 
                                       pairs_per_sample=pairs_per_sample,
                                       src_filter_str=src_filter_str,
                                       pairs_filter_str=pairs_filter_str,
                                       src_collections=src_collections,
                                       pairs_collections=pairs_collections,
                                       exclude_src_collections=exclude_src_collections,
                                       exclude_pairs_collections=exclude_pairs_collections
                                      )

pairing_ids = [{'src_id': pair['src_node']['_id'], 'pair_ids': [pair_node['_id'] for pair_node in pair['pair_nodes']]} for pair in pairings]
total_pairs = sum([len(p["pair_ids"]) for p in pairing_ids])
print(f'Total combinations: {total_pairs}')
print(json.dumps(pairing_ids, indent=4))

Total combinations: 2640
[
    {
        "src_id": "APTProfileArtifact/obap_apt_001",
        "pair_ids": [
            "StorylineArtifact/obap_storyline_001",
            "RedTeamDocArtifact/obap_red_doc_001",
            "ProcessLogArtifact/4390",
            "SprintLogArtifact/2024",
            "RobotLogArtifact/2133",
            "OrchestrationPlanArtifact/obap_orchestration_seq_001",
            "ProcessLogArtifact/4389",
            "RobotLogArtifact/2130",
            "RobotLogArtifact/2128",
            "LearningObjectivesArtifact/obap_dlo_001",
            "ConfluenceDocArtifact/obap_confluence_page",
            "RobotLogArtifact/2132",
            "ProcessLogArtifact/4396",
            "SprintLogArtifact/2025",
            "FeedbackImplementationArtifact/obap_feedback_impl_001",
            "VMDeploymentArtifact/obap_deployment_001",
            "ProcessLogArtifact/4388",
            "DeadRangeValidationArtifact/obap_dead_range_001",
            "ExecutionCertificationArtifact/obap_cert_001",
            "HandbookAssemblyArtifact/obap_handbook_assembly_001",
            "IPOEArtifact/obap_intel_ipoe_001",
            "ProcessLogArtifact/4392",
            "LiveExecutionArtifact/obap_live_exec_001",
            "IntelArtifact/obap_design_intel_001",
            "IntelInjectArtifact/obap_intel_injects_001",
            "BlueHandbookArtifact/obap_blue_handbook_001",
            "RobotLogArtifact/2134",
            "ExecutionPlanArtifact/2991",
            "CustomerRequirementArtifact/obap_cust_req_001",
            "RobotLogArtifact/2136",
            "QualityAssuranceArtifact/obap_final_qa_001",
            "MPNetworkArtifact/obap_mission_partner_001",
            "SprintLogArtifact/2026",
            "SprintLogArtifact/2027",
            "AreaOfOperationArtifact/obap_aor_001",
            "ExecutionResultsArtifact/obap_final_exec_001",
            "RobotLogArtifact/2127",
            "ProcessLogArtifact/4387",
            "TestFeedbackArtifact/obap_test_feedback_001",
            "RangeCapabilityArtifact/obap_range_cap_001"
        ]
    },
    {
        "src_id": "AreaOfOperationArtifact/obap_aor_001",
        "pair_ids": [
            "WhiteCellHandbookArtifact/obap_white_handbook_001",
            "RobotLogArtifact/2130",
            "RangeInputArtifact/obap_range_inputs_001",
            "ProcessLogArtifact/4396",
            "IPOEArtifact/obap_intel_ipoe_001",
            "ExecutionPlanArtifact/2991",
            "TigerTeamArtifact/obap_tiger_team_001",
            "ContentDeliveryArtifact/obap_content_delivery_001",
            "RobotLogArtifact/2134",
            "IntelArtifact/obap_design_intel_001",
            "RobotLogArtifact/2129",
            "SprintLogArtifact/2023",
            "ProcessLogArtifact/4395",
            "RobotLogArtifact/2127",
            "DeliveryArtifact/obap_delivery_001",
            "OrchestrationPlanArtifact/obap_orchestration_seq_001",
            "SprintLogArtifact/2026",
            "ProcessLogArtifact/4391",
            "SprintLogArtifact/2024",
            "RobotLogArtifact/2128",
            "StorylineArtifact/obap_storyline_001",
            "RangeRequestArtifact/obap_range_req_001",
            "CustomerRequirementArtifact/obap_cust_req_001",
            "ExecutionResultsArtifact/obap_final_exec_001",
            "VMDeploymentArtifact/obap_deployment_001",
            "OperationNotesArtifact/obap_op_notes_001",
            "RobotLogArtifact/2132",
            "ProcessLogArtifact/4389",
            "ProcessLogArtifact/4388",
            "MPNetworkArtifact/obap_mission_partner_001",
            "RedHandbookArtifact/obap_handbook_entry",
            "ProcessLogArtifact/4392",
            "ProcessLogArtifact/4393",
            "ProcessLogArtifact/4394",
            "OPFORInputArtifact/obap_opfor_inputs_001",
            "ProcessLogArtifact/4390",
            "ProcessLogArtifact/4387",
            "LiveExecutionArtifact/obap_live_exec_001",
            "OSArtifact/obap_target_os_001",
            "CapabilityRequestArtifact/obap_cap_req_001"
        ]
    },
    {
        "src_id": "BlueHandbookArtifact/obap_blue_handbook_001",
        "pair_ids": [
            "LiveExecutionArtifact/obap_live_exec_001",
            "DeliveryArtifact/obap_delivery_001",
            "ProcessLogArtifact/4395",
            "SprintLogArtifact/2024",
            "RangeRequestArtifact/obap_range_req_001",
            "CampaignPlanArtifact/obap_campaign_plan_v1",
            "FeedbackImplementationArtifact/obap_feedback_impl_001",
            "RedHandbookArtifact/obap_handbook_entry",
            "RobotLogArtifact/2132",
            "ScenarioNarrativeArtifact/obap_narrative_001",
            "RobotLogArtifact/2130",
            "ExecutionCertificationArtifact/obap_cert_001",
            "NetworkMapArtifact/obap_network_map_001",
            "RobotLogArtifact/2131",
            "ProcessLogArtifact/4394",
            "ProcessLogArtifact/4391",
            "IPOEArtifact/obap_intel_ipoe_001",
            "ProcessLogArtifact/4392",
            "StorylineArtifact/obap_storyline_001",
            "CloneMgtArtifact/obap_clone_ops_001",
            "VMDeploymentArtifact/obap_deployment_001",
            "JIRAStoryArtifact/RANGE-847",
            "RobotLogArtifact/2136",
            "ProcessLogArtifact/4388",
            "OPFORInputArtifact/obap_opfor_inputs_001",
            "ProcessLogArtifact/4396",
            "RobotLogArtifact/2135",
            "SprintLogArtifact/2023",
            "ConfluenceDocArtifact/obap_confluence_page",
            "IntelArtifact/obap_design_intel_001",
            "AreaOfOperationArtifact/obap_aor_001",
            "ProcessLogArtifact/4390",
            "RangeCapabilityArtifact/obap_range_cap_001",
            "QualityAssuranceArtifact/obap_final_qa_001",
            "TestLogArtifact/obap_test_run_003",
            "DeadRangeValidationArtifact/obap_dead_range_001",
            "HandbookAssemblyArtifact/obap_handbook_assembly_001",
            "TestFeedbackArtifact/obap_test_feedback_001",
            "ProcessLogArtifact/4387",
            "OperationNotesArtifact/obap_op_notes_001"
        ]
    },
    {
        "src_id": "CampaignPlanArtifact/obap_campaign_plan_v1",
        "pair_ids": [
            "TigerTeamArtifact/obap_tiger_team_001",
            "HandbookAssemblyArtifact/obap_handbook_assembly_001",
            "ProcessLogArtifact/4389",
            "RobotLogArtifact/2128",
            "ProcessLogArtifact/4387",
            "FeedbackImplementationArtifact/obap_feedback_impl_001",
            "RangeInputArtifact/obap_range_inputs_001",
            "RobotLogArtifact/2136",
            "AreaOfOperationArtifact/obap_aor_001",
            "OrchestrationPlanArtifact/obap_orchestration_seq_001",
            "SprintLogArtifact/2024",
            "MPNetworkArtifact/obap_mission_partner_001",
            "RobotLogArtifact/2129",
            "IntelArtifact/obap_design_intel_001",
            "OperationNotesArtifact/obap_op_notes_001",
            "CloneMgtArtifact/obap_clone_ops_001",
            "RobotLogArtifact/2132",
            "ConfluenceDocArtifact/obap_confluence_page",
            "DeliveryArtifact/obap_delivery_001",
            "WhiteCellHandbookArtifact/obap_white_handbook_001",
            "ProcessLogArtifact/4390",
            "ScenarioNarrativeArtifact/obap_narrative_001",
            "RobotLogArtifact/2127",
            "QualityAssuranceArtifact/obap_final_qa_001",
            "RobotLogArtifact/2133",
            "LearningObjectivesArtifact/obap_dlo_001",
            "SprintLogArtifact/2025",
            "ProcessLogArtifact/4393",
            "CapabilityRequestArtifact/obap_cap_req_001",
            "ProcessLogArtifact/4392",
            "ProcessLogArtifact/4395",
            "JIRAStoryArtifact/RANGE-847",
            "ContentDeliveryArtifact/obap_content_delivery_001",
            "RedHandbookArtifact/obap_handbook_entry",
            "BlueHandbookArtifact/obap_blue_handbook_001",
            "SprintLogArtifact/2023",
            "SprintLogArtifact/2027",
            "TestFeedbackArtifact/obap_test_feedback_001",
            "APTProfileArtifact/obap_apt_001",
            "ProcessLogArtifact/4394"
        ]
    },
    {
        "src_id": "CapabilityRequestArtifact/obap_cap_req_001",
        "pair_ids": [
            "TigerTeamArtifact/obap_tiger_team_001",
            "DeadRangeValidationArtifact/obap_dead_range_001",
            "OPFORInputArtifact/obap_opfor_inputs_001",
            "ProcessLogArtifact/4396",
            "RangeCapabilityArtifact/obap_range_cap_001",
            "SprintLogArtifact/2023",
            "ScenarioNarrativeArtifact/obap_narrative_001",
            "RobotLogArtifact/2129",
            "ConfluenceDocArtifact/obap_confluence_page",
            "MPNetworkArtifact/obap_mission_partner_001",
            "ExecutionPlanArtifact/2991",
            "SprintLogArtifact/2026",
            "WhiteCellHandbookArtifact/obap_white_handbook_001",
            "OrchestrationPlanArtifact/obap_orchestration_seq_001",
            "VMDeploymentArtifact/obap_deployment_001",
            "RobotLogArtifact/2130",
            "RobotLogArtifact/2134",
            "RedHandbookArtifact/obap_handbook_entry",
            "OperationNotesArtifact/obap_op_notes_001",
            "ProcessLogArtifact/4388",
            "HandbookAssemblyArtifact/obap_handbook_assembly_001",
            "TestLogArtifact/obap_test_run_003",
            "ProcessLogArtifact/4390",
            "BlueHandbookArtifact/obap_blue_handbook_001",
            "FeedbackImplementationArtifact/obap_feedback_impl_001",
            "SprintLogArtifact/2024",
            "ExecutionCertificationArtifact/obap_cert_001",
            "CustomerRequirementArtifact/obap_cust_req_001",
            "JIRAStoryArtifact/RANGE-847",
            "LearningObjectivesArtifact/obap_dlo_001",
            "ProcessLogArtifact/4389",
            "IPOEArtifact/obap_intel_ipoe_001",
            "IntelInjectArtifact/obap_intel_injects_001",
            "ProcessLogArtifact/4392",
            "RobotLogArtifact/2132",
            "RobotLogArtifact/2135",
            "RobotLogArtifact/2128",
            "RedTeamDocArtifact/obap_red_doc_001",
            "StorylineArtifact/obap_storyline_001",
            "RobotLogArtifact/2127"
        ]
    },
    {
        "src_id": "CloneMgtArtifact/obap_clone_ops_001",
        "pair_ids": [
            "VMDeploymentArtifact/obap_deployment_001",
            "OSArtifact/obap_target_os_001",
            "DeliveryArtifact/obap_delivery_001",
            "CustomerRequirementArtifact/obap_cust_req_001",
            "OperationNotesArtifact/obap_op_notes_001",
            "DeadRangeValidationArtifact/obap_dead_range_001",
            "QualityAssuranceArtifact/obap_final_qa_001",
            "RobotLogArtifact/2127",
            "CapabilityRequestArtifact/obap_cap_req_001",
            "RobotLogArtifact/2134",
            "RobotLogArtifact/2131",
            "ExecutionResultsArtifact/obap_final_exec_001",
            "ScenarioNarrativeArtifact/obap_narrative_001",
            "ProcessLogArtifact/4395",
            "ProcessLogArtifact/4391",
            "SprintLogArtifact/2023",
            "ProcessLogArtifact/4392",
            "AreaOfOperationArtifact/obap_aor_001",
            "RobotLogArtifact/2130",
            "NetworkMapArtifact/obap_network_map_001",
            "RobotLogArtifact/2135",
            "OrchestrationPlanArtifact/obap_orchestration_seq_001",
            "RobotLogArtifact/2133",
            "SprintLogArtifact/2024",
            "RangeInputArtifact/obap_range_inputs_001",
            "TestFeedbackArtifact/obap_test_feedback_001",
            "ProcessLogArtifact/4393",
            "WhiteCellHandbookArtifact/obap_white_handbook_001",
            "ContentDeliveryArtifact/obap_content_delivery_001",
            "ExecutionPlanArtifact/2991",
            "FeedbackImplementationArtifact/obap_feedback_impl_001",
            "RangeRequestArtifact/obap_range_req_001",
            "CampaignPlanArtifact/obap_campaign_plan_v1",
            "IntelArtifact/obap_design_intel_001",
            "RobotLogArtifact/2136",
            "TigerTeamArtifact/obap_tiger_team_001",
            "LearningObjectivesArtifact/obap_dlo_001",
            "SprintLogArtifact/2025",
            "ProcessLogArtifact/4389",
            "RobotLogArtifact/2132"
        ]
    },
    {
        "src_id": "ConfluenceDocArtifact/obap_confluence_page",
        "pair_ids": [
            "IntelInjectArtifact/obap_intel_injects_001",
            "MPNetworkArtifact/obap_mission_partner_001",
            "RangeInputArtifact/obap_range_inputs_001",
            "RobotLogArtifact/2136",
            "IntelArtifact/obap_design_intel_001",
            "ProcessLogArtifact/4389",
            "RobotLogArtifact/2134",
            "TestLogArtifact/obap_test_run_003",
            "DeliveryArtifact/obap_delivery_001",
            "RobotLogArtifact/2131",
            "RobotLogArtifact/2132",
            "RobotLogArtifact/2135",
            "RangeRequestArtifact/obap_range_req_001",
            "VMDeploymentArtifact/obap_deployment_001",
            "SprintLogArtifact/2025",
            "SprintLogArtifact/2026",
            "LiveExecutionArtifact/obap_live_exec_001",
            "QualityAssuranceArtifact/obap_final_qa_001",
            "TigerTeamArtifact/obap_tiger_team_001",
            "APTProfileArtifact/obap_apt_001",
            "FeedbackImplementationArtifact/obap_feedback_impl_001",
            "ExecutionPlanArtifact/2991",
            "OPFORInputArtifact/obap_opfor_inputs_001",
            "ProcessLogArtifact/4396",
            "RobotLogArtifact/2130",
            "StorylineArtifact/obap_storyline_001",
            "NetworkMapArtifact/obap_network_map_001",
            "OrchestrationPlanArtifact/obap_orchestration_seq_001",
            "ProcessLogArtifact/4390",
            "ProcessLogArtifact/4387",
            "ProcessLogArtifact/4394",
            "RobotLogArtifact/2128",
            "RobotLogArtifact/2127",
            "HandbookAssemblyArtifact/obap_handbook_assembly_001",
            "IPOEArtifact/obap_intel_ipoe_001",
            "AreaOfOperationArtifact/obap_aor_001",
            "ScenarioNarrativeArtifact/obap_narrative_001",
            "RedHandbookArtifact/obap_handbook_entry",
            "ProcessLogArtifact/4392",
            "DeadRangeValidationArtifact/obap_dead_range_001"
        ]
    },
    {
        "src_id": "ContentDeliveryArtifact/obap_content_delivery_001",
        "pair_ids": [
            "QualityAssuranceArtifact/obap_final_qa_001",
            "LearningObjectivesArtifact/obap_dlo_001",
            "ExecutionPlanArtifact/2991",
            "RobotLogArtifact/2136",
            "IPOEArtifact/obap_intel_ipoe_001",
            "RangeInputArtifact/obap_range_inputs_001",
            "SprintLogArtifact/2026",
            "BlueHandbookArtifact/obap_blue_handbook_001",
            "SprintLogArtifact/2027",
            "VMDeploymentArtifact/obap_deployment_001",
            "SprintLogArtifact/2023",
            "OperationNotesArtifact/obap_op_notes_001",
            "RangeRequestArtifact/obap_range_req_001",
            "TestFeedbackArtifact/obap_test_feedback_001",
            "LiveExecutionArtifact/obap_live_exec_001",
            "RangeCapabilityArtifact/obap_range_cap_001",
            "OPFORInputArtifact/obap_opfor_inputs_001",
            "ProcessLogArtifact/4392",
            "MPNetworkArtifact/obap_mission_partner_001",
            "OSArtifact/obap_target_os_001",
            "RobotLogArtifact/2133",
            "SprintLogArtifact/2024",
            "RobotLogArtifact/2135",
            "AreaOfOperationArtifact/obap_aor_001",
            "CapabilityRequestArtifact/obap_cap_req_001",
            "NetworkMapArtifact/obap_network_map_001",
            "IntelInjectArtifact/obap_intel_injects_001",
            "ProcessLogArtifact/4387",
            "ProcessLogArtifact/4394",
            "CustomerRequirementArtifact/obap_cust_req_001",
            "RobotLogArtifact/2131",
            "ProcessLogArtifact/4389",
            "RedHandbookArtifact/obap_handbook_entry",
            "DeadRangeValidationArtifact/obap_dead_range_001",
            "SprintLogArtifact/2025",
            "RobotLogArtifact/2127",
            "ScenarioNarrativeArtifact/obap_narrative_001",
            "RobotLogArtifact/2134",
            "ProcessLogArtifact/4396",
            "DeliveryArtifact/obap_delivery_001"
        ]
    },
    {
        "src_id": "CustomerRequirementArtifact/obap_cust_req_001",
        "pair_ids": [
            "RangeCapabilityArtifact/obap_range_cap_001",
            "RobotLogArtifact/2135",
            "ProcessLogArtifact/4393",
            "ProcessLogArtifact/4392",
            "OPFORInputArtifact/obap_opfor_inputs_001",
            "VMDeploymentArtifact/obap_deployment_001",
            "SprintLogArtifact/2025",
            "RobotLogArtifact/2128",
            "QualityAssuranceArtifact/obap_final_qa_001",
            "SprintLogArtifact/2024",
            "JIRAStoryArtifact/RANGE-847",
            "RobotLogArtifact/2131",
            "RangeRequestArtifact/obap_range_req_001",
            "ConfluenceDocArtifact/obap_confluence_page",
            "IPOEArtifact/obap_intel_ipoe_001",
            "IntelArtifact/obap_design_intel_001",
            "ContentDeliveryArtifact/obap_content_delivery_001",
            "SprintLogArtifact/2027",
            "ProcessLogArtifact/4387",
            "RobotLogArtifact/2127",
            "RedHandbookArtifact/obap_handbook_entry",
            "NetworkMapArtifact/obap_network_map_001",
            "MPNetworkArtifact/obap_mission_partner_001",
            "TestLogArtifact/obap_test_run_003",
            "ProcessLogArtifact/4394",
            "ExecutionResultsArtifact/obap_final_exec_001",
            "StorylineArtifact/obap_storyline_001",
            "LearningObjectivesArtifact/obap_dlo_001",
            "CampaignPlanArtifact/obap_campaign_plan_v1",
            "SprintLogArtifact/2023",
            "BlueHandbookArtifact/obap_blue_handbook_001",
            "CloneMgtArtifact/obap_clone_ops_001",
            "RobotLogArtifact/2132",
            "LiveExecutionArtifact/obap_live_exec_001",
            "ProcessLogArtifact/4396",
            "DeliveryArtifact/obap_delivery_001",
            "ProcessLogArtifact/4388",
            "ProcessLogArtifact/4389",
            "HandbookAssemblyArtifact/obap_handbook_assembly_001",
            "RobotLogArtifact/2129"
        ]
    },
    {
        "src_id": "DeadRangeValidationArtifact/obap_dead_range_001",
        "pair_ids": [
            "RobotLogArtifact/2133",
            "JIRAStoryArtifact/RANGE-847",
            "OPFORInputArtifact/obap_opfor_inputs_001",
            "HandbookAssemblyArtifact/obap_handbook_assembly_001",
            "SprintLogArtifact/2025",
            "RobotLogArtifact/2135",
            "OSArtifact/obap_target_os_001",
            "SprintLogArtifact/2023",
            "OperationNotesArtifact/obap_op_notes_001",
            "ProcessLogArtifact/4390",
            "RobotLogArtifact/2129",
            "ProcessLogArtifact/4393",
            "TigerTeamArtifact/obap_tiger_team_001",
            "RobotLogArtifact/2131",
            "TestFeedbackArtifact/obap_test_feedback_001",
            "ExecutionCertificationArtifact/obap_cert_001",
            "RangeCapabilityArtifact/obap_range_cap_001",
            "ProcessLogArtifact/4387",
            "ProcessLogArtifact/4389",
            "ContentDeliveryArtifact/obap_content_delivery_001",
            "RedTeamDocArtifact/obap_red_doc_001",
            "CloneMgtArtifact/obap_clone_ops_001",
            "ProcessLogArtifact/4394",
            "StorylineArtifact/obap_storyline_001",
            "RobotLogArtifact/2130",
            "RangeRequestArtifact/obap_range_req_001",
            "RobotLogArtifact/2128",
            "ProcessLogArtifact/4388",
            "ProcessLogArtifact/4392",

## Run Experiment Table

In [54]:
def gen_consistency_score(data):
    return 100 / (data['exact_match_range'] + data['partial_match_range'] + data['inc_kv_counts_range'] + data['missed_range'] + 1)
    
def gen_model_overall_score(data):
    return ( (data['avg_exact_match']/(data['exact_match_range'] + 1)) + ((data['avg_partial_correct'] - (data['avg_avg_inc_kv_counts']*10)) / (data['partial_correct_range']) + 1) ) / data['total_expected']

In [71]:
pd.options.display.max_columns = None
grid_results_df = pd.read_json('grid_results_102925_01.json', lines=True)
print(len(grid_results_df))
grid_results_df_sorted_avgc = grid_results_df.sort_values(by=['avg_avg_inc_kv_counts', 'avg_exact_match', 'avg_partial_correct', 'avg_runtime'], ascending=[True, False, False, True])

grid_results_df_sorted_avgc

52

,model1,model2,temp1,temp2,iterations,total_expected,avg_exact_match,max_exact_match,min_exact_match,exact_match_range,avg_partial_correct,max_partial_correct,min_partial_correct,partial_correct_range,avg_incorrect,max_incorrect,min_incorrect,incorrect_range,avg_missed,max_missed,min_missed,missed_range,avg_avg_inc_kv_counts,max_inc_kv_counts,min_inc_kv_counts,inc_kv_counts_range,avg_runtime,max_runtime,min_runtime
21,gpt-oss:120b,llama3.3:70b,0.8,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,98.2,99,97,2,7.8,9,7,2,1.0,1,1,0,0.0,0,0,0,0.091589,2,0,2,1067.176583,1360.888094,785.717360
7,gpt-oss:120b,llama3.3:70b,0.2,1.0,"[{'total_expected': 107, 'total_exact_match': ...",107,98.0,99,97,2,8.0,9,7,2,1.0,1,1,0,0.0,0,0,0,0.093458,2,0,2,1082.975957,1270.013120,865.711584
38,gemma3:27b-it-qat,llama3.3:70b,0.2,1.0,"[{'total_expected': 107, 'total_exact_match': ...",107,97.8,98,97,1,8.2,9,8,1,1.0,1,1,0,0.0,0,0,0,0.095327,2,0,2,580.918283,832.393458,394.555745
13,gpt-oss:120b,llama3.3:70b,0.5,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,97.8,98,97,1,8.2,9,8,1,1.0,1,1,0,0.0,0,0,0,0.095327,2,0,2,1123.911848,1334.686665,807.669128
6,gpt-oss:120b,llama3.3:70b,0.2,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,97.8,98,97,1,8.2,9,8,1,1.0,1,1,0,0.0,0,0,0,0.095327,2,0,2,1230.720032,1319.612471,1137.171237
46,gemma3:27b-it-qat,llama3.3:70b,0.5,1.0,"[{'total_expected': 107, 'total_exact_match': ...",107,97.6,99,96,3,8.4,10,7,3,1.0,1,1,0,0.0,0,0,0,0.097196,2,0,2,465.095439,596.584615,403.328087
28,gpt-oss:120b,llama3.3:70b,1.0,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,97.6,99,96,3,8.4,10,7,3,1.0,1,1,0,0.0,0,0,0,0.097196,2,0,2,1025.875565,1116.193441,955.260882
12,gpt-oss:120b,llama3.3:70b,0.5,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,97.6,99,97,2,8.4,9,7,2,1.0,1,1,0,0.0,0,0,0,0.097196,2,0,2,1192.209603,1368.962952,898.869082
22,gpt-oss:120b,llama3.3:70b,0.8,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,97.6,98,97,1,8.4,9,8,1,1.0,1,1,0,0.0,0,0,0,0.097196,2,0,2,1238.972950,1387.843138,1049.611440
51,gemma3:27b-it-qat,llama3.3:70b,0.8,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,97.4,98,97,1,8.6,9,8,1,1.0,1,1,0,0.0,0,0,0,0.099065,2,0,2,652.391110,782.246993,444.142475
35,gemma3:27b-it-qat,llama3.3:70b,0.2,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,97.4,98,97,1,8.6,9,8,1,1.0,1,1,0,0.0,0,0,0,0.099065,2,0,2,758.553212,877.285597,616.129490
44,gemma3:27b-it-qat,llama3.3:70b,0.5,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,97.4,98,97,1,8.6,9,8,1,1.0,1,1,0,0.0,0,0,0,0.099065,2,0,2,783.504347,850.531203,594.715707
20,gpt-oss:120b,llama3.3:70b,0.8,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,97.4,99,97,2,8.6,9,7,2,1.0,1,1,0,0.0,0,0,0,0.099065,2,0,2,841.932786,1304.597582,662.433253
15,gpt-oss:120b,llama3.3:70b,0.5,1.0,"[{'total_expected': 107, 'total_exact_match': ...",107,97.4,98,96,2,8.6,10,8,2,1.0,1,1,0,0.0,0,0,0,0.099065,2,0,2,1016.556939,1140.407412,807.777368
14,gpt-oss:120b,llama3.3:70b,0.5,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,97.4,99,94,5,8.6,12,7,5,1.0,1,1,0,0.0,0,0,0,0.099065,2,0,2,1239.400931,1345.982982,1134.596124
43,gemma3:27b-it-qat,llama3.3:70b,0.5,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,97.2,98,97,1,8.8,9,8,1,1.0,1,1,0,0.0,0,0,0,0.100935,2,0,2,777.400907,852.485108,638.385070
36,gemma3:27b-it-qat,llama3.3:70b,0.2,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,97.2,99,96,3,8.8,10,7,3,1.0,1,1,0,0.0,0,0,0,0.100935,2,0,2,781.534462,894.953198,742.511659
4,gpt-oss:120b,llama3.3:70b,0.2,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,97.2,98,97,1,8.8,9,8,1,1.0,1,1,0,0.0,0,0,0,0.100935,2,0,2,1147.814365,1365.844880,917.884709
27,gpt-oss:120b,llama3.3:70b,1.0,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,97.0,97,97,0,9.0,9,9,0,1.0,1,1,0,0.0,0,0,0,0.102804,2,0,2,927.375894,1024.011149,655.261205
8,gpt-oss:120b,gemma3:27b-it-qat,0.5,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,97.2,98,96,2,8.2,9,7,2,1.6,2,1,1,0.0,0,0,0,0.106542,2,0,2,738.970055,798.846152,640.039332
29,gpt-oss:120b,llama3.3:70b,1.0,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,96.6,97,96,1,9.4,10,9,1,1.0,1,1,0,0.0,0,0,0,0.106542,2,0,2,1039.173959,1193.129299,882.324168
45,gemma3:27b-it-qat,llama3.3:70b,0.5,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,96.4,97,96,1,9.6,10,9,1,1.0,1,1,0,0.0,0,0,0,0.108411,2,0,2,791.453322,875.377847,552.563733
31,gpt-oss:120b,llama3.3:70b,1.0,1.0,"[{'total_expected': 107, 'total_exact_match': ...",107,96.4,98,94,4,9.6,12,8,4,1.0,1,1,0,0.0,0,0,0,0.108411,2,0,2,854.925433,1122.835678,558.246623
5,gpt-oss:120b,llama3.3:70b,0.2,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,96.4,98,95,3,9.6,11,8,3,1.0,1,1,0,0.0,0,0,0,0.108411,2,0,2,1222.481609,1367.812744,1053.576961
37,gemma3:27b-it-qat,llama3.3:70b,0.2,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,96.2,98,95,3,9.8,11,8,3,1.0,1,1,0,0.0,0,0,0,0.110280,2,0,2,823.412446,853.696087,726.677871
49,gemma3:27b-it-qat,gemma3:27b-it-qat,0.8,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,95.6,98,92,6,9.4,12,8,4,1.2,2,1,1,0.8,2,0,2,0.111095,2,0,2,497.660136,560.186870,405.844488
47,gemma3:27b-it-qat,gemma3:27b-it-qat,0.8,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,96.4,97,95,2,9.2,10,8,2,1.4,2,1,1,0.0,0,0,0,0.112150,2,0,2,445.536275,561.980511,275.983008
23,gpt-oss:120b,gemma3:27b-it-qat,1.0,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,96.6,98,95,3,8.6,10,7,3,1.8,2,1,1,0.0,0,0,0,0.114019,2,0,2,758.023490,924.705593,632.024809
17,gpt-oss:120b,gemma3:27b-it-qat,0.8,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,96.2,98,94,4,9.4,11,8,3,1.4,2,1,1,0.0,0,0,0,0.114019,2,0,2,619.135368,647.667495,587.939289
16,gpt-oss:120b,gemma3:27b-it-qat,0.8,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,95.8,97,95,2,9.4,10,8,2,1.8,2,1,1,0.0,0,0,0,0.121495,2,0,2,657.907567,738.781969,612.264050
26,gpt-oss:120b,gemma3:27b-it-qat,1.0,1.0,"[{'total_expected': 107, 'total_exact_match': ...",107,93.8,96,90,6,10.0,11,9,2,1.6,2,1,1,1.6,5,0,5,0.125212,2,0,2,614.414710,802.906059,494.979727
2,gpt-oss:120b,gemma3:27b-it-qat,0.2,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,94.6,97,93,4,10.6,12,9,3,1.4,2,1,1,0.4,1,0,1,0.125745,2,0,2,936.420003,978.883708,789.847077
48,gemma3:27b-it-qat,gemma3:27b-it-qat,0.8,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,95.2,98,93,5,10.0,12,8,4,1.8,2,1,1,0.0,0,0,0,0.127103,2,0,2,501.741056,561.665318,414.825481
9,gpt-oss:120b,gemma3:27b-it-qat,0.5,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,95.0,97,94,3,10.4,11,9,2,1.6,2,1,1,0.0,0,0,0,0.127103,2,0,2,906.665872,1024.270237,784.077300
19,gpt-oss:120b,gemma3:27b-it-qat,0.8,1.0,"[{'total_expected': 107, 'total_exact_match': ...",107,93.2,96,91,5,10.4,13,8,5,1.4,2,1,1,2.0,4,0,4,0.127481,3,0,3,631.315763,714.683485,575.862661
0,gpt-oss:120b,gemma3:27b-it-qat,0.2,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,95.2,96,94,2,9.8,10,9,1,2.0,3,1,2,0.0,0,0,0,0.128972,2,0,2,953.992982,990.021583,860.267521
50,gemma3:27b-it-qat,gemma3:27b-it-qat,0.8,1.0,"[{'total_expected': 107, 'total_exact_match': ...",107,94.0,96,92,4,9.6,10,8,2,2.0,2,2,0,1.4,3,1,2,0.130697,3,0,3,381.389938,553.997893,246.030978
30,gemma3:27b-it-qat,gemma3:27b-it-qat,0.2,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,95.2,98,94,4,9.6,11,8,3,2.2,3,1,2,0.0,0,0,0,0.130841,2,0,2,325.388145,379.152908,242.999101
33,gemma3:27b-it-qat,gemma3:27b-it-qat,0.2,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,95.0,97,91,6,9.6,12,8,4,2.2,3,1,2,0.2,1,0,1,0.131159,2,0,2,457.678925,564.145168,392.854750
34,gemma3:27b-it-qat,gemma3:27b-it-qat,0.2,1.0,"[{'total_expected': 107, 'total_exact_match': ...",107,94.4,96,93,3,10.4,12,9,3,1.8,2,1,1,0.4,1,0,1,0.131335,2,0,2,462.977101,564.247254,372.850281
3,gpt-oss:120b,gemma3:27b-it-qat,0.2,1.0,"[{'total_expected': 107, 'total_exact_match': ...",107,93.4,96,89,7,10.8,15,8,7,1.6,2,1,1,1.2,4,0,4,0.132259,2,0,2,637.361641,779.150487,575.300609
18,gpt-oss:120b,gemma3:27b-it-qat,0.8,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,94.4,96,93,3,10.2,12,8,4,2.0,2,2,0,0.4,1,0,1,0.133186,2,0,2,685.067803,818.988318,611.118262
32,gemma3:27b-it-qat,gemma3:27b-it-qat,0.2,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,94.8,99,93,6,10.0,12,7,5,2.2,3,1,2,0.0,0,0,0,0.134579,2,0,2,449.588241,562.410453,377.197595
10,gpt-oss:120b,gemma3:27b-it-qat,0.5,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,94.2,98,92,6,10.6,13,8,5,1.8,2,1,1,0.4,2,0,2,0.135042,3,0,3,884.420018,1022.588932,755.870879
40,gemma3:27b-it-qat,gemma3:27b-it-qat,0.5,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,94.4,97,93,4,10.6,12,8,4,2.0,3,1,2,0.0,0,0,0,0.136449,2,0,2,547.921010,569.206436,475.135953
25,gpt-oss:120b,gemma3:27b-it-qat,1.0,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,94.2,95,93,2,11.0,12,10,2,1.8,2,1,1,0.0,0,0,0,0.136449,2,0,2,820.890027,920.672135,687.863423
39,gemma3:27b-it-qat,gemma3:27b-it-qat,0.5,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,94.4,96,93,3,10.4,11,9,2,2.2,3,2,1,0.0,0,0,0,0.138318,2,0,2,386.712163,570.008005,258.658549
1,gpt-oss:120b,gemma3:27b-it-qat,0.2,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,94.4,95,93,2,10.4,11,10,1,2.2,3,1,2,0.0,0,0,0,0.138318,2,0,2,954.123742,990.314311,860.644684
24,gpt-oss:120b,gemma3:27b-it-qat,1.0,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,94.0,95,93,2,10.8,12,10,2,2.2,3,2,1,0.0,0,0,0,0.142056,2,0,2,863.249965,961.371206,704.014464
41,gemma3:27b-it-qat,gemma3:27b-it-qat,0.5,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,94.0,96,92,4,10.4,12,9,3,2.4,3,1,2,0.2,1,0,1,0.142250,2,0,2,546.968219,567.069901,474.156749
42,gemma3:27b-it-qat,gemma3:27b-it-qat,0.5,1.0,"[{'total_expected': 107, 'total_exact_match': ...",107,92.0,93,90,3,10.8,12,10,2,2.2,3,1,2,2.0,3,1,2,0.144664,2,0,2,438.375434,561.821273,250.490734
11,gpt-oss:120b,gemma3:27b-it-qat,0.5,1.0,"[{'total_expected': 107, 'total_exact_match': ...",107,91.8,94,88,6,12.0,15,9,6,2.0,2,2,0,1.2,2,0,2,0.153105,3,0,3,751.496617,945.217900,611.743134

In [63]:
grid_results_df['model_score'] = gen_model_overall_score(grid_results_df)
grid_results_df_sorted_score = grid_results_df.sort_values(by='model_score', ascending=False)
grid_results_df_sorted_score

,model1,model2,temp1,temp2,iterations,total_expected,avg_exact_match,max_exact_match,min_exact_match,exact_match_range,avg_partial_correct,max_partial_correct,min_partial_correct,partial_correct_range,avg_incorrect,max_incorrect,min_incorrect,incorrect_range,avg_missed,max_missed,min_missed,missed_range,avg_avg_inc_kv_counts,max_inc_kv_counts,min_inc_kv_counts,inc_kv_counts_range,avg_runtime,max_runtime,min_runtime,model_score
28,gemma3:27b-it-qat,llama3.3:70b,1.0,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,96.4,98,94,4,9.6,12,8,4,1.0,1,1,0,0.0,0,0,0,0.108411,2,0,2,0:05:31.939283,0:05:34.608645,0:05:29.419585,0.002171
22,gemma3:27b-it-qat,llama3.3:70b,0.8,1.0,"[{'total_expected': 107, 'total_exact_match': ...",107,95.8,98,94,4,10.2,12,8,4,1.0,1,1,0,0.0,0,0,0,0.114019,2,0,2,0:05:30.993555,0:05:33.003883,0:05:27.306079,0.001949
19,gemma3:27b-it-qat,llama3.3:70b,0.8,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,96.4,98,95,3,9.6,11,8,3,1.0,1,1,0,0.0,0,0,0,0.108411,2,0,2,0:05:32.841466,0:05:38.293548,0:05:29.168391,0.001794
7,gemma3:27b-it-qat,llama3.3:70b,0.2,1.0,"[{'total_expected': 107, 'total_exact_match': ...",107,94.6,96,92,4,11.4,14,10,4,1.0,1,1,0,0.0,0,0,0,0.125234,2,0,2,0:05:32.358153,0:05:35.941668,0:05:29.402114,0.001623
29,gemma3:27b-it-qat,llama3.3:70b,1.0,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,95.6,97,94,3,10.4,12,9,3,1.0,1,1,0,0.0,0,0,0,0.115888,2,0,2,0:05:30.431961,0:05:33.402913,0:05:27.543133,0.001598
5,gemma3:27b-it-qat,llama3.3:70b,0.2,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,95.6,97,94,3,10.4,12,9,3,1.0,1,1,0,0.0,0,0,0,0.115888,2,0,2,0:05:34.750004,0:05:37.476138,0:05:31.233308,0.001598
13,gemma3:27b-it-qat,llama3.3:70b,0.5,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,96.0,97,95,2,10.0,11,9,2,1.0,1,1,0,0.0,0,0,0,0.112150,2,0,2,0:05:32.421534,0:05:39.342626,0:05:29.670604,0.001458
21,gemma3:27b-it-qat,llama3.3:70b,0.8,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,96.0,97,95,2,10.0,11,9,2,1.0,1,1,0,0.0,0,0,0,0.112150,2,0,2,0:05:30.293560,0:05:36.063808,0:05:27.088733,0.001458
27,gemma3:27b-it-qat,llama3.3:70b,1.0,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,96.0,97,95,2,10.0,11,9,2,1.0,1,1,0,0.0,0,0,0,0.112150,2,0,2,0:05:33.971406,0:05:42.841781,0:05:29.339271,0.001458
18,gemma3:27b-it-qat,gemma3:27b-it-qat,0.8,1.0,"[{'total_expected': 107, 'total_exact_match': ...",107,89.4,92,87,5,15.2,18,12,6,2.4,3,2,1,0.0,0,0,0,0.190654,3,0,3,0:04:12.250873,0:04:14.887393,0:04:09.466573,0.001392
11,gemma3:27b-it-qat,gemma3:27b-it-qat,0.5,1.0,"[{'total_expected': 107, 'total_exact_match': ...",107,90.6,93,89,4,13.2,15,11,4,3.2,4,3,1,0.0,0,0,0,0.186916,3,0,3,0:04:30.818322,0:04:32.387428,0:04:27.786342,0.001383
20,gemma3:27b-it-qat,llama3.3:70b,0.8,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,94.4,96,93,3,11.6,13,10,3,1.0,1,1,0,0.0,0,0,0,0.127103,2,0,2,0:05:30.467750,0:05:34.192501,0:05:27.576682,0.001377
12,gemma3:27b-it-qat,llama3.3:70b,0.5,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,96.4,97,96,1,9.6,10,9,1,1.0,1,1,0,0.0,0,0,0,0.108411,2,0,2,0:05:36.084089,0:05:47.561038,0:05:30.279075,0.001341
24,gemma3:27b-it-qat,gemma3:27b-it-qat,1.0,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,91.0,92,90,2,13.4,15,11,4,2.6,4,2,2,0.0,0,0,0,0.173832,2,0,2,0:04:11.616298,0:04:13.735660,0:04:09.776851,0.001325
4,gemma3:27b-it-qat,llama3.3:70b,0.2,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,96.2,97,96,1,9.8,10,9,1,1.0,1,1,0,0.0,0,0,0,0.110280,2,0,2,0:05:34.672980,0:05:42.273702,0:05:30.853247,0.001312
14,gemma3:27b-it-qat,llama3.3:70b,0.5,1.0,"[{'total_expected': 107, 'total_exact_match': ...",107,94.8,96,94,2,11.2,12,10,2,1.0,1,1,0,0.0,0,0,0,0.123364,2,0,2,0:05:33.135783,0:05:36.419077,0:05:30.272339,0.001274
6,gemma3:27b-it-qat,llama3.3:70b,0.2,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,94.4,96,93,3,11.4,12,10,2,1.2,2,1,1,0.0,0,0,0,0.128972,2,0,2,0:05:33.161217,0:05:36.723539,0:05:29.845178,0.001255
26,gemma3:27b-it-qat,gemma3:27b-it-qat,1.0,1.0,"[{'total_expected': 107, 'total_exact_match': ...",107,89.8,92,88,4,14.2,16,12,4,3.0,4,2,2,0.0,0,0,0,0.192523,3,0,3,0:04:11.597962,0:04:15.445214,0:04:08.827376,0.001238
3,gemma3:27b-it-qat,gemma3:27b-it-qat,0.2,1.0,"[{'total_expected': 107, 'total_exact_match': ...",107,90.0,91,89,2,14.4,16,12,4,2.6,4,1,3,0.0,0,0,0,0.183178,2,0,2,0:04:29.117147,0:04:30.584637,0:04:26.925864,0.001197
1,gemma3:27b-it-qat,gemma3:27b-it-qat,0.2,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,90.2,91,89,2,14.2,16,13,3,2.6,3,2,1,0.0,0,0,0,0.181308,2,0,2,0:04:31.176268,0:04:35.465217,0:04:27.823011,0.001102
2,gemma3:27b-it-qat,gemma3:27b-it-qat,0.2,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,89.4,91,88,3,14.8,16,13,3,2.8,4,2,2,0.0,0,0,0,0.192523,3,0,3,0:04:28.722873,0:04:32.748463,0:04:23.383835,0.001055
17,gemma3:27b-it-qat,gemma3:27b-it-qat,0.8,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,90.4,91,90,1,14.2,15,13,2,2.2,3,2,1,0.2,1,0,1,0.174132,2,0,2,0:04:20.804161,0:04:55.394643,0:04:08.993682,0.000998
25,gemma3:27b-it-qat,gemma3:27b-it-qat,1.0,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,89.8,91,88,3,14.4,15,13,2,2.8,4,2,2,0.0,0,0,0,0.186916,2,0,2,0:04:10.783133,0:04:13.764970,0:04:09.487741,0.000995
10,gemma3:27b-it-qat,gemma3:27b-it-qat,0.5,0.8,"[{'total_expected': 107, 'total_exact_match': ...",107,89.2,91,88,3,15.0,16,14,2,2.8,4,2,2,0.0,0,0,0,0.192523,2,0,2,0:04:28.401993,0:04:40.546272,0:04:18.559914,0.000952
16,gemma3:27b-it-qat,gemma3:27b-it-qat,0.8,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,89.2,90,89,1,14.6,15,14,1,3.2,4,3,1,0.0,0,0,0,0.196262,2,0,2,0:04:32.007103,0:04:35.400798,0:04:28.408671,0.000909
0,gemma3:27b-it-qat,gemma3:27b-it-qat,0.2,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,89.2,90,89,1,15.6,16,14,2,2.2,3,2,1,0.0,0,0,0,0.186916,2,0,2,0:04:23.456646,0:04:29.909467,0:04:20.120012,0.000903
9,gemma3:27b-it-qat,gemma3:27b-it-qat,0.5,0.5,"[{'total_expected': 107, 'total_exact_match': ...",107,89.8,90,89,1,14.6,15,14,1,2.6,3,2,1,0.0,0,0,0,0.185047,2,0,2,0:04:26.026949,0:04:29.347502,0:04:22.165784,0.000901
23,gemma3:27b-it-qat,gemma3:27b-it-qat,1.0,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,90.2,91,90,1,14.8,15,14,1,2.0,2,2,0,0.0,0,0,0,0.175701,2,0,2,0:04:13.547230,0:04:17.544776,0:04:09.835099,0.000881
8,gemma3:27b-it-qat,gemma3:27b-it-qat,0.5,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,89.0,89,89,0,15.6,16,15,1,2.4,3,2,1,0.0,0,0,0,0.190654,2,0,2,0:04:25.586958,0:04:33.417535,0:04:18.991792,0.000841
15,gemma3:27b-it-qat,gemma3:27b-it-qat,0.8,0.2,"[{'total_expected': 107, 'total_exact_match': ...",107,89.0,89,89,0,15.8,16,15,1,2.2,3,2,1,0.0,0,0,0,0.188785,2,0,2,0:04:39.108032,0:05:06.518186,0:04:23.342839,0.000829